// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated;

public interface InferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Inference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, float&gt; predictions = 1;</code>
   */
  int getPredictionsCount();
  /**
   * <code>map&lt;string, float&gt; predictions = 1;</code>
   */
  boolean containsPredictions(
      java.lang.String key);
  /**
   * Use {@link #getPredictionsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Float>
  getPredictions();
  /**
   * <code>map&lt;string, float&gt; predictions = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Float>
  getPredictionsMap();
  /**
   * <code>map&lt;string, float&gt; predictions = 1;</code>
   */

  float getPredictionsOrDefault(
      java.lang.String key,
      float defaultValue);
  /**
   * <code>map&lt;string, float&gt; predictions = 1;</code>
   */

  float getPredictionsOrThrow(
      java.lang.String key);
}
