// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated;

public interface TimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Timestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string model_name = 2;</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <code>string model_name = 2;</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <code>string kind = 3;</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <code>string kind = 3;</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <code>string host = 4;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>string host = 4;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>string port = 5;</code>
   * @return The port.
   */
  java.lang.String getPort();
  /**
   * <code>string port = 5;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();

  /**
   * <code>string username = 6;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 6;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 7;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 7;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string databaseName = 8;</code>
   * @return The databaseName.
   */
  java.lang.String getDatabaseName();
  /**
   * <code>string databaseName = 8;</code>
   * @return The bytes for databaseName.
   */
  com.google.protobuf.ByteString
      getDatabaseNameBytes();
}
