// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

/**
 * Protobuf type {@code grpc.CalculatePowerIndexRequest}
 */
public final class CalculatePowerIndexRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.CalculatePowerIndexRequest)
    CalculatePowerIndexRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculatePowerIndexRequest.newBuilder() to construct.
  private CalculatePowerIndexRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculatePowerIndexRequest() {
    datasetId_ = "";
    startDate_ = "";
    endDate_ = "";
    cpStarts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    cpEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CalculatePowerIndexRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculatePowerIndexRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            datasetId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            startDate_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            endDate_ = s;
            break;
          }
          case 32: {

            weeksTrain_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              cpStarts_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            cpStarts_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              cpEnds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            cpEnds_.add(s);
            break;
          }
          case 56: {

            queryModelar_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        cpStarts_ = cpStarts_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        cpEnds_ = cpEnds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.more2020.visual.domain.GrpcAutoGenerated.tools.GrpcProto.internal_static_grpc_CalculatePowerIndexRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.more2020.visual.domain.GrpcAutoGenerated.tools.GrpcProto.internal_static_grpc_CalculatePowerIndexRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.class, eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.Builder.class);
  }

  public static final int DATASET_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object datasetId_;
  /**
   * <code>string dataset_id = 1;</code>
   * @return The datasetId.
   */
  @java.lang.Override
  public java.lang.String getDatasetId() {
    java.lang.Object ref = datasetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datasetId_ = s;
      return s;
    }
  }
  /**
   * <code>string dataset_id = 1;</code>
   * @return The bytes for datasetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDatasetIdBytes() {
    java.lang.Object ref = datasetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datasetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_DATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object startDate_;
  /**
   * <code>string start_date = 2;</code>
   * @return The startDate.
   */
  @java.lang.Override
  public java.lang.String getStartDate() {
    java.lang.Object ref = startDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startDate_ = s;
      return s;
    }
  }
  /**
   * <code>string start_date = 2;</code>
   * @return The bytes for startDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartDateBytes() {
    java.lang.Object ref = startDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int END_DATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object endDate_;
  /**
   * <code>string end_date = 3;</code>
   * @return The endDate.
   */
  @java.lang.Override
  public java.lang.String getEndDate() {
    java.lang.Object ref = endDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endDate_ = s;
      return s;
    }
  }
  /**
   * <code>string end_date = 3;</code>
   * @return The bytes for endDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndDateBytes() {
    java.lang.Object ref = endDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEEKS_TRAIN_FIELD_NUMBER = 4;
  private int weeksTrain_;
  /**
   * <code>int32 weeks_train = 4;</code>
   * @return The weeksTrain.
   */
  @java.lang.Override
  public int getWeeksTrain() {
    return weeksTrain_;
  }

  public static final int CP_STARTS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList cpStarts_;
  /**
   * <code>repeated string cp_starts = 5;</code>
   * @return A list containing the cpStarts.
   */
  public com.google.protobuf.ProtocolStringList
      getCpStartsList() {
    return cpStarts_;
  }
  /**
   * <code>repeated string cp_starts = 5;</code>
   * @return The count of cpStarts.
   */
  public int getCpStartsCount() {
    return cpStarts_.size();
  }
  /**
   * <code>repeated string cp_starts = 5;</code>
   * @param index The index of the element to return.
   * @return The cpStarts at the given index.
   */
  public java.lang.String getCpStarts(int index) {
    return cpStarts_.get(index);
  }
  /**
   * <code>repeated string cp_starts = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cpStarts at the given index.
   */
  public com.google.protobuf.ByteString
      getCpStartsBytes(int index) {
    return cpStarts_.getByteString(index);
  }

  public static final int CP_ENDS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList cpEnds_;
  /**
   * <code>repeated string cp_ends = 6;</code>
   * @return A list containing the cpEnds.
   */
  public com.google.protobuf.ProtocolStringList
      getCpEndsList() {
    return cpEnds_;
  }
  /**
   * <code>repeated string cp_ends = 6;</code>
   * @return The count of cpEnds.
   */
  public int getCpEndsCount() {
    return cpEnds_.size();
  }
  /**
   * <code>repeated string cp_ends = 6;</code>
   * @param index The index of the element to return.
   * @return The cpEnds at the given index.
   */
  public java.lang.String getCpEnds(int index) {
    return cpEnds_.get(index);
  }
  /**
   * <code>repeated string cp_ends = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cpEnds at the given index.
   */
  public com.google.protobuf.ByteString
      getCpEndsBytes(int index) {
    return cpEnds_.getByteString(index);
  }

  public static final int QUERY_MODELAR_FIELD_NUMBER = 7;
  private boolean queryModelar_;
  /**
   * <code>bool query_modelar = 7;</code>
   * @return The queryModelar.
   */
  @java.lang.Override
  public boolean getQueryModelar() {
    return queryModelar_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datasetId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, datasetId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, startDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endDate_);
    }
    if (weeksTrain_ != 0) {
      output.writeInt32(4, weeksTrain_);
    }
    for (int i = 0; i < cpStarts_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cpStarts_.getRaw(i));
    }
    for (int i = 0; i < cpEnds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cpEnds_.getRaw(i));
    }
    if (queryModelar_ != false) {
      output.writeBool(7, queryModelar_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datasetId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, datasetId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, startDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endDate_);
    }
    if (weeksTrain_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, weeksTrain_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cpStarts_.size(); i++) {
        dataSize += computeStringSizeNoTag(cpStarts_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCpStartsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cpEnds_.size(); i++) {
        dataSize += computeStringSizeNoTag(cpEnds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCpEndsList().size();
    }
    if (queryModelar_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, queryModelar_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest)) {
      return super.equals(obj);
    }
    eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest other = (eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest) obj;

    if (!getDatasetId()
        .equals(other.getDatasetId())) return false;
    if (!getStartDate()
        .equals(other.getStartDate())) return false;
    if (!getEndDate()
        .equals(other.getEndDate())) return false;
    if (getWeeksTrain()
        != other.getWeeksTrain()) return false;
    if (!getCpStartsList()
        .equals(other.getCpStartsList())) return false;
    if (!getCpEndsList()
        .equals(other.getCpEndsList())) return false;
    if (getQueryModelar()
        != other.getQueryModelar()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATASET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDatasetId().hashCode();
    hash = (37 * hash) + START_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getStartDate().hashCode();
    hash = (37 * hash) + END_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getEndDate().hashCode();
    hash = (37 * hash) + WEEKS_TRAIN_FIELD_NUMBER;
    hash = (53 * hash) + getWeeksTrain();
    if (getCpStartsCount() > 0) {
      hash = (37 * hash) + CP_STARTS_FIELD_NUMBER;
      hash = (53 * hash) + getCpStartsList().hashCode();
    }
    if (getCpEndsCount() > 0) {
      hash = (37 * hash) + CP_ENDS_FIELD_NUMBER;
      hash = (53 * hash) + getCpEndsList().hashCode();
    }
    hash = (37 * hash) + QUERY_MODELAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getQueryModelar());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.CalculatePowerIndexRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.CalculatePowerIndexRequest)
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.tools.GrpcProto.internal_static_grpc_CalculatePowerIndexRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.tools.GrpcProto.internal_static_grpc_CalculatePowerIndexRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.class, eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.Builder.class);
    }

    // Construct using eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      datasetId_ = "";

      startDate_ = "";

      endDate_ = "";

      weeksTrain_ = 0;

      cpStarts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      cpEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      queryModelar_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.tools.GrpcProto.internal_static_grpc_CalculatePowerIndexRequest_descriptor;
    }

    @java.lang.Override
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest getDefaultInstanceForType() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.getDefaultInstance();
    }

    @java.lang.Override
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest build() {
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest buildPartial() {
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest result = new eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest(this);
      int from_bitField0_ = bitField0_;
      result.datasetId_ = datasetId_;
      result.startDate_ = startDate_;
      result.endDate_ = endDate_;
      result.weeksTrain_ = weeksTrain_;
      if (((bitField0_ & 0x00000001) != 0)) {
        cpStarts_ = cpStarts_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.cpStarts_ = cpStarts_;
      if (((bitField0_ & 0x00000002) != 0)) {
        cpEnds_ = cpEnds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.cpEnds_ = cpEnds_;
      result.queryModelar_ = queryModelar_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest) {
        return mergeFrom((eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest other) {
      if (other == eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.getDefaultInstance()) return this;
      if (!other.getDatasetId().isEmpty()) {
        datasetId_ = other.datasetId_;
        onChanged();
      }
      if (!other.getStartDate().isEmpty()) {
        startDate_ = other.startDate_;
        onChanged();
      }
      if (!other.getEndDate().isEmpty()) {
        endDate_ = other.endDate_;
        onChanged();
      }
      if (other.getWeeksTrain() != 0) {
        setWeeksTrain(other.getWeeksTrain());
      }
      if (!other.cpStarts_.isEmpty()) {
        if (cpStarts_.isEmpty()) {
          cpStarts_ = other.cpStarts_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCpStartsIsMutable();
          cpStarts_.addAll(other.cpStarts_);
        }
        onChanged();
      }
      if (!other.cpEnds_.isEmpty()) {
        if (cpEnds_.isEmpty()) {
          cpEnds_ = other.cpEnds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCpEndsIsMutable();
          cpEnds_.addAll(other.cpEnds_);
        }
        onChanged();
      }
      if (other.getQueryModelar() != false) {
        setQueryModelar(other.getQueryModelar());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object datasetId_ = "";
    /**
     * <code>string dataset_id = 1;</code>
     * @return The datasetId.
     */
    public java.lang.String getDatasetId() {
      java.lang.Object ref = datasetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datasetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataset_id = 1;</code>
     * @return The bytes for datasetId.
     */
    public com.google.protobuf.ByteString
        getDatasetIdBytes() {
      java.lang.Object ref = datasetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datasetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataset_id = 1;</code>
     * @param value The datasetId to set.
     * @return This builder for chaining.
     */
    public Builder setDatasetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datasetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataset_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatasetId() {
      
      datasetId_ = getDefaultInstance().getDatasetId();
      onChanged();
      return this;
    }
    /**
     * <code>string dataset_id = 1;</code>
     * @param value The bytes for datasetId to set.
     * @return This builder for chaining.
     */
    public Builder setDatasetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datasetId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object startDate_ = "";
    /**
     * <code>string start_date = 2;</code>
     * @return The startDate.
     */
    public java.lang.String getStartDate() {
      java.lang.Object ref = startDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string start_date = 2;</code>
     * @return The bytes for startDate.
     */
    public com.google.protobuf.ByteString
        getStartDateBytes() {
      java.lang.Object ref = startDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string start_date = 2;</code>
     * @param value The startDate to set.
     * @return This builder for chaining.
     */
    public Builder setStartDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string start_date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartDate() {
      
      startDate_ = getDefaultInstance().getStartDate();
      onChanged();
      return this;
    }
    /**
     * <code>string start_date = 2;</code>
     * @param value The bytes for startDate to set.
     * @return This builder for chaining.
     */
    public Builder setStartDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      startDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endDate_ = "";
    /**
     * <code>string end_date = 3;</code>
     * @return The endDate.
     */
    public java.lang.String getEndDate() {
      java.lang.Object ref = endDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string end_date = 3;</code>
     * @return The bytes for endDate.
     */
    public com.google.protobuf.ByteString
        getEndDateBytes() {
      java.lang.Object ref = endDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string end_date = 3;</code>
     * @param value The endDate to set.
     * @return This builder for chaining.
     */
    public Builder setEndDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string end_date = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndDate() {
      
      endDate_ = getDefaultInstance().getEndDate();
      onChanged();
      return this;
    }
    /**
     * <code>string end_date = 3;</code>
     * @param value The bytes for endDate to set.
     * @return This builder for chaining.
     */
    public Builder setEndDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endDate_ = value;
      onChanged();
      return this;
    }

    private int weeksTrain_ ;
    /**
     * <code>int32 weeks_train = 4;</code>
     * @return The weeksTrain.
     */
    @java.lang.Override
    public int getWeeksTrain() {
      return weeksTrain_;
    }
    /**
     * <code>int32 weeks_train = 4;</code>
     * @param value The weeksTrain to set.
     * @return This builder for chaining.
     */
    public Builder setWeeksTrain(int value) {
      
      weeksTrain_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 weeks_train = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeeksTrain() {
      
      weeksTrain_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList cpStarts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCpStartsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cpStarts_ = new com.google.protobuf.LazyStringArrayList(cpStarts_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @return A list containing the cpStarts.
     */
    public com.google.protobuf.ProtocolStringList
        getCpStartsList() {
      return cpStarts_.getUnmodifiableView();
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @return The count of cpStarts.
     */
    public int getCpStartsCount() {
      return cpStarts_.size();
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @param index The index of the element to return.
     * @return The cpStarts at the given index.
     */
    public java.lang.String getCpStarts(int index) {
      return cpStarts_.get(index);
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cpStarts at the given index.
     */
    public com.google.protobuf.ByteString
        getCpStartsBytes(int index) {
      return cpStarts_.getByteString(index);
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @param index The index to set the value at.
     * @param value The cpStarts to set.
     * @return This builder for chaining.
     */
    public Builder setCpStarts(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCpStartsIsMutable();
      cpStarts_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @param value The cpStarts to add.
     * @return This builder for chaining.
     */
    public Builder addCpStarts(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCpStartsIsMutable();
      cpStarts_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @param values The cpStarts to add.
     * @return This builder for chaining.
     */
    public Builder addAllCpStarts(
        java.lang.Iterable<java.lang.String> values) {
      ensureCpStartsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cpStarts_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpStarts() {
      cpStarts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_starts = 5;</code>
     * @param value The bytes of the cpStarts to add.
     * @return This builder for chaining.
     */
    public Builder addCpStartsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCpStartsIsMutable();
      cpStarts_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList cpEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCpEndsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        cpEnds_ = new com.google.protobuf.LazyStringArrayList(cpEnds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @return A list containing the cpEnds.
     */
    public com.google.protobuf.ProtocolStringList
        getCpEndsList() {
      return cpEnds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @return The count of cpEnds.
     */
    public int getCpEndsCount() {
      return cpEnds_.size();
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @param index The index of the element to return.
     * @return The cpEnds at the given index.
     */
    public java.lang.String getCpEnds(int index) {
      return cpEnds_.get(index);
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cpEnds at the given index.
     */
    public com.google.protobuf.ByteString
        getCpEndsBytes(int index) {
      return cpEnds_.getByteString(index);
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @param index The index to set the value at.
     * @param value The cpEnds to set.
     * @return This builder for chaining.
     */
    public Builder setCpEnds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCpEndsIsMutable();
      cpEnds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @param value The cpEnds to add.
     * @return This builder for chaining.
     */
    public Builder addCpEnds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCpEndsIsMutable();
      cpEnds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @param values The cpEnds to add.
     * @return This builder for chaining.
     */
    public Builder addAllCpEnds(
        java.lang.Iterable<java.lang.String> values) {
      ensureCpEndsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cpEnds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpEnds() {
      cpEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cp_ends = 6;</code>
     * @param value The bytes of the cpEnds to add.
     * @return This builder for chaining.
     */
    public Builder addCpEndsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCpEndsIsMutable();
      cpEnds_.add(value);
      onChanged();
      return this;
    }

    private boolean queryModelar_ ;
    /**
     * <code>bool query_modelar = 7;</code>
     * @return The queryModelar.
     */
    @java.lang.Override
    public boolean getQueryModelar() {
      return queryModelar_;
    }
    /**
     * <code>bool query_modelar = 7;</code>
     * @param value The queryModelar to set.
     * @return This builder for chaining.
     */
    public Builder setQueryModelar(boolean value) {
      
      queryModelar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool query_modelar = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryModelar() {
      
      queryModelar_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.CalculatePowerIndexRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.CalculatePowerIndexRequest)
  private static final eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest();
  }

  public static eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculatePowerIndexRequest>
      PARSER = new com.google.protobuf.AbstractParser<CalculatePowerIndexRequest>() {
    @java.lang.Override
    public CalculatePowerIndexRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculatePowerIndexRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculatePowerIndexRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculatePowerIndexRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

