// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public interface FrechetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.FrechetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string start_date = 1;</code>
   * @return The startDate.
   */
  java.lang.String getStartDate();
  /**
   * <code>string start_date = 1;</code>
   * @return The bytes for startDate.
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string end_date = 2;</code>
   * @return The endDate.
   */
  java.lang.String getEndDate();
  /**
   * <code>string end_date = 2;</code>
   * @return The bytes for endDate.
   */
  com.google.protobuf.ByteString
      getEndDateBytes();

  /**
   * <code>string i = 3;</code>
   * @return The i.
   */
  java.lang.String getI();
  /**
   * <code>string i = 3;</code>
   * @return The bytes for i.
   */
  com.google.protobuf.ByteString
      getIBytes();

  /**
   * <code>string DS_list = 4;</code>
   * @return The dSList.
   */
  java.lang.String getDSList();
  /**
   * <code>string DS_list = 4;</code>
   * @return The bytes for dSList.
   */
  com.google.protobuf.ByteString
      getDSListBytes();

  /**
   * <code>string R = 5;</code>
   * @return The r.
   */
  java.lang.String getR();
  /**
   * <code>string R = 5;</code>
   * @return The bytes for r.
   */
  com.google.protobuf.ByteString
      getRBytes();
}
