// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public interface GetDatasetDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GetDatasetDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data_id = 1;</code>
   * @return The dataId.
   */
  java.lang.String getDataId();
  /**
   * <code>string data_id = 1;</code>
   * @return The bytes for dataId.
   */
  com.google.protobuf.ByteString
      getDataIdBytes();
}
