// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: athForecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting;

/**
 * Protobuf type {@code csv_service.HandleDataResponse}
 */
public final class HandleDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:csv_service.HandleDataResponse)
    HandleDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HandleDataResponse.newBuilder() to construct.
  private HandleDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HandleDataResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HandleDataResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HandleDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              results_ = com.google.protobuf.MapField.newMapField(
                  ResultsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
            results__ = input.readMessage(
                ResultsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            results_.getMutableMap().put(
                results__.getKey(), results__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.AthForecasting.internal_static_csv_service_HandleDataResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetResults();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.AthForecasting.internal_static_csv_service_HandleDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.class, eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.Builder.class);
  }

  public static final int RESULTS_FIELD_NUMBER = 1;
  private static final class ResultsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Float> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Float>newDefaultInstance(
                eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.AthForecasting.internal_static_csv_service_HandleDataResponse_ResultsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.FLOAT,
                0F);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Float> results_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
  internalGetResults() {
    if (results_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ResultsDefaultEntryHolder.defaultEntry);
    }
    return results_;
  }

  public int getResultsCount() {
    return internalGetResults().getMap().size();
  }
  /**
   * <code>map&lt;string, float&gt; results = 1;</code>
   */

  @java.lang.Override
  public boolean containsResults(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetResults().getMap().containsKey(key);
  }
  /**
   * Use {@link #getResultsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Float> getResults() {
    return getResultsMap();
  }
  /**
   * <code>map&lt;string, float&gt; results = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Float> getResultsMap() {
    return internalGetResults().getMap();
  }
  /**
   * <code>map&lt;string, float&gt; results = 1;</code>
   */
  @java.lang.Override

  public float getResultsOrDefault(
      java.lang.String key,
      float defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Float> map =
        internalGetResults().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, float&gt; results = 1;</code>
   */
  @java.lang.Override

  public float getResultsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Float> map =
        internalGetResults().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetResults(),
        ResultsDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Float> entry
         : internalGetResults().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
      results__ = ResultsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse)) {
      return super.equals(obj);
    }
    eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse other = (eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse) obj;

    if (!internalGetResults().equals(
        other.internalGetResults())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetResults().getMap().isEmpty()) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetResults().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code csv_service.HandleDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:csv_service.HandleDataResponse)
      eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.AthForecasting.internal_static_csv_service_HandleDataResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.AthForecasting.internal_static_csv_service_HandleDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.class, eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.Builder.class);
    }

    // Construct using eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableResults().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.AthForecasting.internal_static_csv_service_HandleDataResponse_descriptor;
    }

    @java.lang.Override
    public eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse getDefaultInstanceForType() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse build() {
      eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse buildPartial() {
      eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse result = new eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse(this);
      int from_bitField0_ = bitField0_;
      result.results_ = internalGetResults();
      result.results_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse) {
        return mergeFrom((eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse other) {
      if (other == eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse.getDefaultInstance()) return this;
      internalGetMutableResults().mergeFrom(
          other.internalGetResults());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Float> results_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
    internalGetResults() {
      if (results_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultsDefaultEntryHolder.defaultEntry);
      }
      return results_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
    internalGetMutableResults() {
      onChanged();;
      if (results_ == null) {
        results_ = com.google.protobuf.MapField.newMapField(
            ResultsDefaultEntryHolder.defaultEntry);
      }
      if (!results_.isMutable()) {
        results_ = results_.copy();
      }
      return results_;
    }

    public int getResultsCount() {
      return internalGetResults().getMap().size();
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */

    @java.lang.Override
    public boolean containsResults(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetResults().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float> getResults() {
      return getResultsMap();
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Float> getResultsMap() {
      return internalGetResults().getMap();
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */
    @java.lang.Override

    public float getResultsOrDefault(
        java.lang.String key,
        float defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetResults().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */
    @java.lang.Override

    public float getResultsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetResults().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearResults() {
      internalGetMutableResults().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */

    public Builder removeResults(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableResults().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float>
    getMutableResults() {
      return internalGetMutableResults().getMutableMap();
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */
    public Builder putResults(
        java.lang.String key,
        float value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableResults().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, float&gt; results = 1;</code>
     */

    public Builder putAllResults(
        java.util.Map<java.lang.String, java.lang.Float> values) {
      internalGetMutableResults().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:csv_service.HandleDataResponse)
  }

  // @@protoc_insertion_point(class_scope:csv_service.HandleDataResponse)
  private static final eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse();
  }

  public static eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandleDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<HandleDataResponse>() {
    @java.lang.Override
    public HandleDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HandleDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HandleDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandleDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting.HandleDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

